# Generated by Django 3.1.4 on 2021-01-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0004_multiplechoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicesolutionanswer',
            name='user',
        ),
    ]
