# Generated by Django 3.1.4 on 2020-12-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
