# Generated by Django 3.1.4 on 2020-12-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_solution_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='answer',
        ),
    ]
