# Generated by Django 3.1.4 on 2020-12-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_delete_singlechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='multiple_choice',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
