# Generated by Django 3.1.4 on 2021-01-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0009_flashcard_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='rank',
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, null=True)),
                ('flashcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
