# Generated by Django 3.1.4 on 2021-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0010_auto_20210106_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='rank',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
