# Generated by Django 3.1.4 on 2020-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('workload', models.IntegerField()),
                ('deadline', models.DateField()),
                ('solution', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
