# Generated by Django 3.1.4 on 2021-01-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_choices', '0003_singlechoiceanswer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlechoiceanswer',
            old_name='solution',
            new_name='answer',
        ),
    ]
