# Generated by Django 3.1.4 on 2021-01-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('single_choices', '0004_auto_20210104_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlechoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
