# Generated by Django 3.1.4 on 2021-01-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_choices', '0005_singlechoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlechoiceanswer',
            name='user',
        ),
    ]
